import tkinter as tk
def calculate_product():
    num1=float(entry1.get())
    num2=float(entry2.get())
    result=num1*num2
    result_box.delete(1.0, tk.END)
    result_box.insert(tk.END, str(result))
root=tk.Tk()
root.geometry("400x300")
root.title("Getting Started with Widgets")
label=tk.Label(root,text="This application calculates the product of two numbers.")
label.pack()
label1=tk.Label(root,text="Enter first number:")
label1.pack()
entry1=tk.Entry(root)
entry1.pack()
label2=tk.Label(root,text="Enter second number:")
label2.pack()
entry2=tk.Entry(root)
entry2.pack()
button=tk.Button(root,text="Calculate Product",command=calculate_product)
button.pack()
result_box=tk.Text(root,height=1,width=20)
result_box.pack()
root.mainloop()
